language: ruby
rvm:
  - 2.2.2
services: postgres
before_script:
  - rm config/database.yml
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database yrs_hacks_test;' -U postgres
  - bin/rake db:migrate
