development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: hacks_development

test:
  adapter: postgresql
  encoding: unicode
  database: hacks_test

production:
  adapter: postgresql
  encoding: unicode
  database: hacks_production
