development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: yrs_hacks_development

test:
  adapter: postgresql
  encoding: unicode
  database: yrs_hacks_test

production:
  adapter: postgresql
  encoding: unicode
  database: yrs_hacks_production
